#!/usr/bin/env php
<?php

/**
 * FOOTUP - 0.1.4 - 12.2021
 * *************************
 * Hard Coded by Faustfizz Yous
 * 
 * @package Footup
 * @version 0.1
 * @author Faustfizz Yous <youssoufmbae2@gmail.com>
 */


// Refuse to run when called from php-cgi
if (substr(php_sapi_name(), 0, 3) === 'cgi')
{
	die("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

// Directory Separator
defined("DS") or define("DS", DIRECTORY_SEPARATOR);

// Path to the front controller
define('BASE_PATH', __DIR__ . '/public' . DIRECTORY_SEPARATOR);

/**
 * Le dossier système
 */
defined('SYS_PATH') or define('SYS_PATH', realpath(__DIR__.DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR."core/");

/**
 * Le Dossier ROOT du projet
 */
defined('ROOT_PATH') or define('ROOT_PATH', __DIR__.DIRECTORY_SEPARATOR);

/**
 * @todo Configure ceci pour pointer au dossier contenant vos fichier de configuration
 */
defined('CONFIG_PATH') or define('CONFIG_PATH', __DIR__.DIRECTORY_SEPARATOR.'app/Config'.DIRECTORY_SEPARATOR);
defined('APP_PATH') or define('APP_PATH', CONFIG_PATH."..".DIRECTORY_SEPARATOR);

/**
 * Chargement des classes de configuration
 * =======================================
 * - config système
 * - config utilisateur
 */
include_once SYS_PATH.'Config/Config.php';
include_once CONFIG_PATH.'Config.php';

/**
 * Chargement des chargeurs de classes
 */
include_once SYS_PATH.'Config/Autoload.php';
include_once CONFIG_PATH.'Autoload.php';

/**
 * Démarrer le chargeur de classes
 */
(new \App\Config\Autoload())->register();

/**
 * Initialise la classe de configuration
 */
$config = new \App\Config\Config();

/**
 * Création de quelques constantes importantes
 * ==========================================
 * - le chemin vers le dossier (app)
 * - chemin vers le dossier des vues (app/view)
 * - chemin vers le dossier de téléversement
 */
defined('VIEW_PATH') or define('VIEW_PATH', realpath($config->view_path).DIRECTORY_SEPARATOR);
defined('STORE_DIR') or define('STORE_DIR', realpath($config->store_dir).DIRECTORY_SEPARATOR);
defined('ASSETS_DIR') or define('ASSETS_DIR', realpath($config->assets_dir).DIRECTORY_SEPARATOR);

/**
 * On se positionne dans le dossier public
 */
chdir(BASE_PATH);

/**
 * Démarre le console
 */
$cli = new Footup\Cli\Console();
$cli->run();