<?php

/**
 * Auto generated by Foot Cli
 */

namespace App\Controller{name_space};

{use_header}

class {class_name} extends BaseController
{
    public function index()
    {
        return $this->view("{class_name}", [
            "titre" => "Accueil"
        ]);
    }
    
}
