<?php

/**
 * Auto generated by Foot Cli
 */

namespace {name_space};

use Footup\Http\Request;
use Footup\Http\Response;

class {class_name}
{
    /**
     * Execute the middle --- Function called by the core framework
     *
     * @param Request $request
     * @param Response $response
     * @param callable|\Closure $next to queue middles
     *
     * @return Response|mixed|void -- to continue to the next middle return $next($request, $response),
     * return $response to skip all other middle and return a string or void if you need to stop here
     */
    public function execute(Request $request, Response $response, $next)
    {
        // If you want to use session do $session = Shared::loadSession() or $session = session();
        return $next($request, $response);
    }
}