<?php

/**
 * Auto generated by Foot Cli
 */

namespace App\Migration;

use Footup\Database\Schema\Schema;
use Footup\Database\Schema\Table;
use Footup\Database\Migration;


class {class_name} extends Migration
{
    /**
     * You can use $this->table($tableName)->int('id) inside all these function but the createTable function is a static method
     *
     * @return bool|string|Schema
     */
    protected function up()
    {
        // don't miss the return keyword here
        return Schema::createTable('{table}', function(Table $table){
            $table->int("id")->autoIncrement()->addOption("PRIMARY KEY");
        });
    }

    /**
     * @return bool|string|Schema
     */
    protected function empty()
    {
        return Schema::empty("{table}");
    }

    /**
     * @return bool|string|Schema
     */
    protected function down()
    {
        return Schema::drop("{table}");
    }
}