<?php

/**
 * Auto generated by Foot Cli
 */

namespace App\Seed;

use Footup\Database\Seeder;

class {class_name} extends Seeder
{
    /**
     * You can chain $this->call(AnotherSeeder::class)->call("AnnotherSeed") inside the run method to run others Seeders.
     */

    /**
     * You must implement this method and take care
     * of inserting their data here.
     *
     * @return mixed
     */
    public function run()
    {
        // $data is [field => data] or [ [field => data], [field => data] ]
        $data = [];

        // Use insert for unidimentionnal or insertBatch for multidim
        // You can return or not
        return $this->table("{table}")->insert($data);
    }

}